version: "3.8"
services:
  minio:
    build: .
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data

volumes:
  minio_data:
